name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o seu cÃ³digo
    - name: Checkout do cÃ³digo
      uses: actions/checkout@v4

    # 2. Instala o Java 17 (ou 21, ajuste conforme seu pom.xml)
    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache:maven: true

    # 3. Roda o Maven (Compila e Testa)
    - name: Compilar e Testar com Maven
      run: mvn -B package --file pom.xml

    # (Opcional) Mostra se passou
    - name: Notificar Sucesso
      if: success()
      run: echo "Build Compilado com Sucesso! ðŸš€"
